# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: LUMA_allure

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # clone the repository
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Start X-server
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        Xvfb :99 -screen 0 1900x1000x24 >/dev/null 2>&1 &
        sleep 1

    - name: Run Pytest
      run: |
        DISPLAY=:99 pytest -s -v --alluredir=allure-results
      continue-on-error: true

#    - name: Get Allure history
#      uses: actions/checkout@v2
#      if: always()
#      continue-on-error: true
#      with:
#        # ref -- branch (or tag in some case)
#        ref: gh-pages
#        # local path on a virtual machine
#        path: gh-pages

    - name: Allure Report action
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Commit Allure report
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.MY_TOKEN }}
        PUBLISH_BRANCH: gh-pages-alina
        PUBLISH_DIR: allure-history
